server:
  env: "development"
  host: "127.0.0.1"
  port: 3000
  routes:
    base: "/api"
    generate_image: "/images"
    discord_summary: "/discord-summary/:id"
    monitoring: "/monitoring"

monitoring:
  discord:
    - name: "Arisoutre"
      url: "https://arisoutre.antredesloutres.fr/healthcheck"
    - name: "Mineotter"
      url: "https://mineotter.antredesloutres.fr/healthcheck"
    - name: "Mateloutre"
      url: "https://mateloutre.antredesloutres.fr/healthcheck"

  minecraft:
    - name: "La Vanilla S4"
      host: "antredesloutres.fr"
      port: 25565
    - name: "Île de berk"
      host: "antredesloutres.fr"
      port: 25564
    - name: "Creatif"
      host: "antredesloutres.fr"
      port: 25566
    - name: "La Vanilla S1"
      host: "antredesloutres.fr"
      port: 25567
    - name: "Serveur de dev"
      host: "antredesloutres.fr"
      port: 25569
    - name: "Ottergames"
      host: "antredesloutres.fr"
      port: 25599

  api:
    - name: "OtterlyApi"
      url: "https://otterlyapi.antredesloutres.fr"

  self_hosted:
    - name: "Pocketbase"
      url: "https://pocketbase.antredesloutres.fr/api/health"
    - name: "Portainer"
      url: "https://portainer.antredesloutres.fr"
    - name: "Nginx proxy manager"
      url: "https://nginx.antredesloutres.fr"
    - name: "Wikijs"
      url: "https://wiki.antredesloutres.fr"

  site:
    - name: "Astroloutre"
      url: "https://antredesloutres.fr"

  http: []
