server:
  host: "127.0.0.1"
  port: 3000
  routes:
    base: "/api"
    generate_image: "/images"
    discord_summary: "/discord-summary/:id"

api:
  base_url: "https://otterlyapi.antredesloutres.fr/api"
  endpoints:
    discord_user: "/utilisateurs_discord"
    discord_stats: "/utilisateurs_discord/stats"
