use axum::{
    routing::get,
    Json, Router,
};
use serde::{Deserialize, Serialize};
use std::net::SocketAddr;
use tower_http::services::ServeDir;
use utoipa::{OpenApi, ToSchema};
use utoipa_swagger_ui::SwaggerUi;

#[derive(Serialize, Deserialize, ToSchema, Clone)]
struct Item {
    id: i32,
    name: String,
    description: Option<String>,
}

#[derive(Serialize, Deserialize, ToSchema, Clone)]
struct CreateItem {
    name: String,
    description: Option<String>,
}

#[derive(OpenApi)]
#[openapi(
    paths(get_items, create_item),
    components(schemas(Item, CreateItem))
)]
struct ApiDoc;

/// Get a list of items
#[utoipa::path(
    get,
    path = "/api/items",
    responses(
        (status = 200, description = "List all items", body = [Item])
    )
)]
async fn get_items() -> Json<Vec<Item>> {
    let items = vec![
        Item {
            id: 1,
            name: "First Item".to_string(),
            description: Some("This is the first item".to_string()),
        },
        Item {
            id: 2,
            name: "Second Item".to_string(),
            description: None,
        },
    ];
    Json(items)
}

/// Create a new item
#[utoipa::path(
    post,
    path = "/api/items",
    request_body = CreateItem,
    responses(
        (status = 201, description = "Item created successfully", body = Item)
    )
)]
async fn create_item(Json(payload): Json<CreateItem>) -> (axum::http::StatusCode, Json<Item>) {
    let item = Item {
        id: 3, // In a real app, this would be generated by a DB
        name: payload.name,
        description: payload.description,
    };
    (axum::http::StatusCode::CREATED, Json(item))
}

#[tokio::main]
async fn main() {
    // Build our application with routes
    let app = Router::new()
        // API routes
        .route("/api/items", get(get_items).post(create_item))
        // Swagger UI
        .merge(SwaggerUi::new("/swagger-ui").url("/api-docs/openapi.json", ApiDoc::openapi()))
        // Serve static files from the "public" directory
        .fallback_service(ServeDir::new("public"));

    // Run it with hyper
    let addr = SocketAddr::from(([127, 0, 0, 1], 3000));
    println!("listening on http://{}", addr);
    println!("Swagger UI available at http://{}/swagger-ui", addr);

    let listener = tokio::net::TcpListener::bind(addr).await.unwrap();
    axum::serve(listener, app).await.unwrap();
}
